[package]
name = "crates-index"
description = "Library for retrieving and interacting with the crates.io index"
version = "0.15.3"
homepage = "https://lib.rs/crates-index"
authors = ["Corey Farwell <coreyf@rwell.org>", "Kornel <kornel@geekhood.net>"]
keywords = ["packaging", "index", "dependencies", "crate", "meta"]
categories = ["development-tools", "database"]
repository = "https://github.com/frewsxcv/rust-crates-index"
license = "Apache-2.0"
documentation = "https://docs.rs/crates-index/"
edition = "2018"

[dependencies]
git2 = "0.13.0"
glob = "0.3.0"
hex = { version = "0.4.2", features = ["serde"] }
home = "0.5.3"
memchr = "2.3.3"
semver = "0.10.0"
serde = "1.0.105"
serde_derive = "1.0.105"
serde_json = "1.0.48"
smol_str = { version = "0.1.15", features = ["serde"] }

[dev-dependencies]
tempdir = "0.3.7"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
vendored-openssl = ["git2/vendored-openssl"]
